In [ ]:
# install dependencies
!pip install python-dotenv==1.0.1
!pip install newspaper3k
!pip install lxml_html_clean

Collecting python-dotenv==1.0.1
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.0.1
Collecting newspaper3k
  Downloading newspaper3k-0.2.8-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (4.13.4)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (11.2.1)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (6.0.2)
Collecting cssselect>=0.9.2 (from newspaper3k)
  Downloading cssselect-1.3.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (5.4.0)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (3.9.1)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (2.32.3)
Collecting feedparser>=5.2.1 (from newspaper3k)
  Downloading feedparser-6.0.11-py3-none-any.whl.metadata (2.4 kB)
Collecting tldextract>=2.0.1 (from newspaper3k)
  Downloading tldextract-5.3.0-py3-none-any.whl.metadata (11 kB)
Collecting feedfinder2>=0.0.4 (from newspaper3k)
  Downloading feedfinder2-0.0.4.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Collecting jieba3k>=0.35.1 (from newspaper3k)
  Downloading jieba3k-0.35.1.zip (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 37.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from newspaper3k) (2.9.0.post0)
Collecting tinysegmenter==0.3 (from newspaper3k)
  Downloading tinysegmenter-0.3.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.13.2)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Collecting sgmllib3k (from feedparser>=5.2.1->newspaper3k)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>=3.2.1->newspaper3k) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>=3.2.1->newspaper3k) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>=3.2.1->newspaper3k) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk>=3.2.1->newspaper3k) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->newspaper3k) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->newspaper3k) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->newspaper3k) (2025.1.31)
Collecting requests-file>=1.4 (from tldextract>=2.0.1->newspaper3k)
  Downloading requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.11/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.18.0)
Downloading newspaper3k-0.2.8-py3-none-any.whl (211 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 3.1 MB/s eta 0:00:00
Downloading cssselect-1.3.0-py3-none-any.whl (18 kB)
Downloading feedparser-6.0.11-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 5.1 MB/s eta 0:00:00
Downloading tldextract-5.3.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 6.7 MB/s eta 0:00:00
Downloading requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Building wheels for collected packages: tinysegmenter, feedfinder2, jieba3k, sgmllib3k
  Building wheel for tinysegmenter (setup.py) ... done
  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-py3-none-any.whl size=13540 sha256=c389fce41a1acddbcf2bb8126122e9e4f3fc75527c92711537eb2e5f54f7c883
  Stored in directory: /root/.cache/pip/wheels/fc/ab/f8/cce3a9ae6d828bd346be695f7ff54612cd22b7cbd7208d68f3
  Building wheel for feedfinder2 (setup.py) ... done
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-py3-none-any.whl size=3341 sha256=9ecee79e7e1f9257a371cf4694ebeb83ec95dd79875fcac51d78ab9c093d4131
  Stored in directory: /root/.cache/pip/wheels/80/d5/72/9cd9eccc819636436c6a6e59c22a0fb1ec167beef141f56491
  Building wheel for jieba3k (setup.py) ... done
  Created wheel for jieba3k: filename=jieba3k-0.35.1-py3-none-any.whl size=7398380 sha256=2749c9b654d2cb2fde99cb132de0c9ce26883f1a8a755288cc568b7466e48ebb
  Stored in directory: /root/.cache/pip/wheels/3a/a1/46/8e68055c1713f9c4598774c15ad0541f26d5425ee7423b6493
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=334a491c3d4b186d88e344e79d04e1db3e35b0b3649720bef630b0c87a1cb4db
  Stored in directory: /root/.cache/pip/wheels/3b/25/2a/105d6a15df6914f4d15047691c6c28f9052cc1173e40285d03
Successfully built tinysegmenter feedfinder2 jieba3k sgmllib3k
Installing collected packages: tinysegmenter, sgmllib3k, jieba3k, feedparser, cssselect, requests-file, feedfinder2, tldextract, newspaper3k
Successfully installed cssselect-1.3.0 feedfinder2-0.0.4 feedparser-6.0.11 jieba3k-0.35.1 newspaper3k-0.2.8 requests-file-2.1.0 sgmllib3k-1.0.0 tinysegmenter-0.3 tldextract-5.3.0
Collecting lxml_html_clean
  Downloading lxml_html_clean-0.4.2-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from lxml_html_clean) (5.4.0)
Downloading lxml_html_clean-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: lxml_html_clean
Successfully installed lxml_html_clean-0.4.2

In [ ]:
# import libraries
import newspaper
from newspaper import Article
import requests

In [ ]:
# Use a free API to retrieve news articles that match a provided query
query = "(sustainability AND business AND climate AND impact)"  #the article titles, descriptions, and content are all searched for their fit with this query
start_date = "2025-04-23"
end_date = "2025-04-30"
sort_by = "relevancy"  #choose either relevancy, popularity, publishedAt
NEWS_API_KEY= # <your free NewsAPI key>

url = f"https://newsapi.org/v2/everything?q={query}&from={start_date}&to={end_date}&sortBy={sort_by}&apiKey={NEWS_API_KEY}"
r = requests.get(url)

In [ ]:
# look a data
articles = r.json()['articles']
articles[:3]

[{'source': {'id': 'the-next-web', 'name': 'The Next Web'},
  'author': 'Andrea Hak',
  'title': 'This VC-backed network is on a mission to tackle the well-being crises with tech',
  'description': 'Last year, NN Group and Rubio Impact Ventures launched the NN Social Innovation Startup Award providing grants and mentoring to startups to tackle mental, physical, and financial well-being challenges with tech-backed solutions. Over 360 startups applied. Bas…',
  'url': 'https://thenextweb.com/news/vc-network-mission-tackle-well-being-crisis-tech',
  'urlToImage': 'https://img-cdn.tnwcdn.com/image/tnw-blurple?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2025%2F04%2FStartUpAwardGroup2024-1.jpg&signature=11b76590271e6d7a4e7b47a8dffc4264',
  'publishedAt': '2025-04-24T08:24:38Z',
  'content': 'Last year, NN Group and Rubio Impact Ventures launched the NN Social Innovation Startup Award providing grants and mentoring to startups to tackle mental, physical, and financial well-being challenge… [+6072 chars]'},
 {'source': {'id': 'the-next-web', 'name': 'The Next Web'},
  'author': 'Thomas Macaulay',
  'title': 'Meet the Dutch tech stars speaking at TNW Conference',
  'description': 'As our favourite Dutch holiday approaches, TNW is celebrating the tech titans shaping the future in the Netherlands. Our beloved home country is the proud parent of a prodigious brood of digital talent. It’s given birth to cultivated meat, raised Booking.com …',
  'url': 'https://thenextweb.com/news/meet-dutch-tech-tech-startup-leaders-tnw-conference',
  'urlToImage': 'https://img-cdn.tnwcdn.com/image/tnw-blurple?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2025%2F04%2FUntitled-design-31.jpg&signature=6ad3f2d75a325f94e185b04bbb882514',
  'publishedAt': '2025-04-24T18:26:57Z',
  'content': 'As our favourite Dutch holiday approaches, TNW is celebrating the tech titans shaping the future in the Netherlands.\r\nOur beloved home country is the proud parent of a prodigious brood of digital tal… [+8164 chars]'},
 {'source': {'id': None, 'name': 'Forbes'},
  'author': 'Joan Michelson, Contributor, \n Joan Michelson, Contributor\n https://www.forbes.com/sites/joanmichelson2/',
  'title': 'What Business Can Do To Address Climate Crisis – Despite Trump’s Actions',
  'description': 'Consumers want business to address the climate crisis, and are willing to pay more for sustainable products. Here are ideas for companies from top women business leaders.',
  'url': 'https://www.forbes.com/sites/joanmichelson2/2025/04/29/what-business-can-do-to-address-climate-crisis--despite-trumps-actions/',
  'urlToImage': 'https://imageio.forbes.com/specials-images/imageserve/681038bf625ef2237a974fce/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
  'publishedAt': '2025-04-29T11:30:00Z',
  'content': "Rosie Austin speaking w panel looking on at Earth Day Women's Summit - 4-22-2025 (l to r: Joan ... More Michelson, Helle Bank Jorgensen, Rosie Austin, Danielle Azoulay, Jana Gerber\r\nKaren Campbell Ph… [+6394 chars]"}]

In [ ]:
# total number of articles retrieved
len(articles)

74

In [ ]:
# cleaning the 'source name' field
for article in articles:
    article['source'] = article['source']['name']

In [ ]:
# look at cleaned data
articles[0]

{'source': 'The Next Web',
 'author': 'Andrea Hak',
 'title': 'This VC-backed network is on a mission to tackle the well-being crises with tech',
 'description': 'Last year, NN Group and Rubio Impact Ventures launched the NN Social Innovation Startup Award providing grants and mentoring to startups to tackle mental, physical, and financial well-being challenges with tech-backed solutions. Over 360 startups applied. Bas…',
 'url': 'https://thenextweb.com/news/vc-network-mission-tackle-well-being-crisis-tech',
 'urlToImage': 'https://img-cdn.tnwcdn.com/image/tnw-blurple?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2025%2F04%2FStartUpAwardGroup2024-1.jpg&signature=11b76590271e6d7a4e7b47a8dffc4264',
 'publishedAt': '2025-04-24T08:24:38Z',
 'content': 'Last year, NN Group and Rubio Impact Ventures launched the NN Social Innovation Startup Award providing grants and mentoring to startups to tackle mental, physical, and financial well-being challenge… [+6072 chars]'}

In [ ]:
import pandas as pd
import numpy as np

# create a dataframe - each row represents an article
df = pd.DataFrame.from_dict(articles)

In [ ]:
# subset to only the first 10 rows for testing
head = df.head(10)
head.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,The Next Web,Andrea Hak,This VC-backed network is on a mission to tack...,"Last year, NN Group and Rubio Impact Ventures ...",https://thenextweb.com/news/vc-network-mission...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2025-04-24T08:24:38Z,"Last year, NN Group and Rubio Impact Ventures ..."
1,The Next Web,Thomas Macaulay,Meet the Dutch tech stars speaking at TNW Conf...,"As our favourite Dutch holiday approaches, TNW...",https://thenextweb.com/news/meet-dutch-tech-te...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2025-04-24T18:26:57Z,"As our favourite Dutch holiday approaches, TNW..."
2,Forbes,"Joan Michelson, Contributor, \n Joan Michelson...",What Business Can Do To Address Climate Crisis...,Consumers want business to address the climate...,https://www.forbes.com/sites/joanmichelson2/20...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T11:30:00Z,Rosie Austin speaking w panel looking on at Ea...
3,Forbes,"Jamie Houston, Forbes Councils Member, \n Jami...",2025 Carbon Market: Three Things To Watch,Biodiversity could become the next major front...,https://www.forbes.com/councils/forbesbusiness...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T13:15:00Z,Jamie Houston is CEO of Aurora Sustainable Lan...
4,TechRadar,Taran Rai,Sustainability Week: Lean manufacturing: the m...,Here’s why lean manufacturing holds the key to...,https://www.techradar.com/pro/sustainability-w...,https://cdn.mos.cms.futurecdn.net/CbPbcNWdQekm...,2025-04-24T14:19:17Z,"In today’s climate-aware world, sustainability..."

In [ ]:
# filter data further
keywords = ['sustainability', 'sustainable', 'business', 'climate', 'impact']

filtered_df = head[
    (head['title'].str.contains('|'.join(keywords), case=False)) |
    (head['description'].str.contains('|'.join(keywords), case=False)) |
    (head['content'].str.contains('|'.join(keywords), case=False))
    ]

In [ ]:
filtered_df

,source,author,title,description,url,urlToImage,publishedAt,content
0,The Next Web,Andrea Hak,This VC-backed network is on a mission to tack...,"Last year, NN Group and Rubio Impact Ventures ...",https://thenextweb.com/news/vc-network-mission...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2025-04-24T08:24:38Z,"Last year, NN Group and Rubio Impact Ventures ..."
2,Forbes,"Joan Michelson, Contributor, \n Joan Michelson...",What Business Can Do To Address Climate Crisis...,Consumers want business to address the climate...,https://www.forbes.com/sites/joanmichelson2/20...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T11:30:00Z,Rosie Austin speaking w panel looking on at Ea...
3,Forbes,"Jamie Houston, Forbes Councils Member, \n Jami...",2025 Carbon Market: Three Things To Watch,Biodiversity could become the next major front...,https://www.forbes.com/councils/forbesbusiness...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T13:15:00Z,Jamie Houston is CEO of Aurora Sustainable Lan...
4,TechRadar,Taran Rai,Sustainability Week: Lean manufacturing: the m...,Here’s why lean manufacturing holds the key to...,https://www.techradar.com/pro/sustainability-w...,https://cdn.mos.cms.futurecdn.net/CbPbcNWdQekm...,2025-04-24T14:19:17Z,"In today’s climate-aware world, sustainability..."
5,Forbes,"Rob Kaplan, Contributor, \n Rob Kaplan, Contri...",Three Zones Of Safety For Investors In Uncerta...,Could now be a moment of opportunity for inves...,https://www.forbes.com/sites/robkaplan/2025/04...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T13:41:27Z,Could now be a moment of opportunity for inves...
6,Forbes,"Andi Cross, Forbes Councils Member, \n Andi Cr...",The Future Of Investment: How Purpose-Driven B...,Impact investing proves that capital can be a ...,https://www.forbes.com/councils/forbesbusiness...,https://imageio.forbes.com/specials-images/ima...,2025-04-23T13:45:00Z,Andi Cross is the Founder of impact consultanc...
7,Forbes,"David Hessekiel, Contributor, \n David Hesseki...","Sustainable Marketing: Speak To Consumers, Not...",Valuable advice for marketers on effectively c...,https://www.forbes.com/sites/davidhessekiel/20...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T13:02:59Z,What a wonderful world this would be if consum...
8,Forbes,"Marshall Shepherd, Senior Contributor, \n Mars...",Rowen Foundation Sees A Pathway To Sustainable...,Rowen Foundation is developing a research and ...,https://www.forbes.com/sites/marshallshepherd/...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T11:16:18Z,An artist rendition of the future Rowen commun...
9,Forbes,"Namita Gupta-Hehl, Brand Contributor, \n Namit...",How Cloud ERP And AI Are Powering The Future O...,Cloud ERP and AI are uniquely positioned to he...,https://www.forbes.com/sites/sap/2025/04/28/ho...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T13:27:29Z,Innovations in cloud ERP and AI are uniquely p...

In [ ]:
# observe how filtering worked
head.iloc[1].description

'As our favourite Dutch holiday approaches, TNW is celebrating the tech titans shaping the future in the Netherlands. Our beloved home country is the proud parent of a prodigious brood of digital talent. It’s given birth to cultivated meat, raised Booking.com …'

In [ ]:
# use AI to filter further
# create a .env file


# # Uncomment the following code to write an environment file with your free OpenAI and Github tokens
# %%writefile .env

# OPENAI_API_KEY= <your free openai api key>
# GITHUB_TOKEN= <your free github token>

Writing .env

In [ ]:
import os
import dotenv
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(), override=True)

os.environ.get('OPENAI_API_KEY')

from openai import OpenAI

token = os.environ.get('GITHUB_TOKEN')
endpoint = "https://models.inference.ai.azure.com"
model_name = "gpt-4o-mini"

client = OpenAI(
    base_url=endpoint,
    api_key=token
)

In [ ]:
from pydantic import BaseModel

class ArticleEval(BaseModel):
    rating: int
    rationale: str

In [ ]:
# rate the articles based on their relevance using AI
responses = []
topic = "innovative business solutions to climate change."

for i in range(filtered_df.shape[0]):

  title = filtered_df.iloc[i]['title']
  descr = filtered_df.iloc[i]['description']
  base_messages = [
      {"role": "developer", "content": "You are a helpful AI assistant who will be asked to rate articles on a scale from 1 to 10 based on "
                                        "their relevance to a provided topic of interest. You will be provided the article title and description, "
                                        "as well as the topic of interest"},
      {"role": "user", "content": (f"Please provide a rating for the article with the following title and description based on how relevant "
                                  f"it is to {topic}: \n\n Article Title: {title} \n\n Article Description:{descr}")},
      {"role": "user", "content": "Please also provide two sentances explaining how you decided on this rating."}
  ]

  reply = client.beta.chat.completions.parse(
                messages=base_messages,
                temperature=1.0,
                top_p=1.0,
                max_tokens=1000,
                model=model_name,
                response_format=ArticleEval
            )
  responses.append(reply.choices[0].message.content)

In [ ]:
# format responses
import ast

new_list = []
for r in responses:
  new_list.append(ast.literal_eval(r))

#create a new dataframe from responses
responses_df = pd.DataFrame.from_dict(new_list)

# concatenate the two dataframes
next_df = pd.concat([filtered_df.reset_index(), responses_df], axis=1)
next_df.drop('index', axis=1, inplace=True)
next_df

,source,author,title,description,url,urlToImage,publishedAt,content,rating,rationale
0,The Next Web,Andrea Hak,This VC-backed network is on a mission to tack...,"Last year, NN Group and Rubio Impact Ventures ...",https://thenextweb.com/news/vc-network-mission...,https://img-cdn.tnwcdn.com/image/tnw-blurple?f...,2025-04-24T08:24:38Z,"Last year, NN Group and Rubio Impact Ventures ...",4,The article discusses innovative tech solution...
1,Forbes,"Joan Michelson, Contributor, \n Joan Michelson...",What Business Can Do To Address Climate Crisis...,Consumers want business to address the climate...,https://www.forbes.com/sites/joanmichelson2/20...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T11:30:00Z,Rosie Austin speaking w panel looking on at Ea...,8,The article directly addresses innovative busi...
2,Forbes,"Jamie Houston, Forbes Councils Member, \n Jami...",2025 Carbon Market: Three Things To Watch,Biodiversity could become the next major front...,https://www.forbes.com/councils/forbesbusiness...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T13:15:00Z,Jamie Houston is CEO of Aurora Sustainable Lan...,6,"The article discusses the carbon market, which..."
3,TechRadar,Taran Rai,Sustainability Week: Lean manufacturing: the m...,Here’s why lean manufacturing holds the key to...,https://www.techradar.com/pro/sustainability-w...,https://cdn.mos.cms.futurecdn.net/CbPbcNWdQekm...,2025-04-24T14:19:17Z,"In today’s climate-aware world, sustainability...",8,"The article discusses lean manufacturing, whic..."
4,Forbes,"Rob Kaplan, Contributor, \n Rob Kaplan, Contri...",Three Zones Of Safety For Investors In Uncerta...,Could now be a moment of opportunity for inves...,https://www.forbes.com/sites/robkaplan/2025/04...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T13:41:27Z,Could now be a moment of opportunity for inves...,5,The article discusses investment opportunities...
5,Forbes,"Andi Cross, Forbes Councils Member, \n Andi Cr...",The Future Of Investment: How Purpose-Driven B...,Impact investing proves that capital can be a ...,https://www.forbes.com/councils/forbesbusiness...,https://imageio.forbes.com/specials-images/ima...,2025-04-23T13:45:00Z,Andi Cross is the Founder of impact consultanc...,8,"The article discusses impact investing, which ..."
6,Forbes,"David Hessekiel, Contributor, \n David Hesseki...","Sustainable Marketing: Speak To Consumers, Not...",Valuable advice for marketers on effectively c...,https://www.forbes.com/sites/davidhessekiel/20...,https://imageio.forbes.com/specials-images/ima...,2025-04-29T13:02:59Z,What a wonderful world this would be if consum...,6,The article discusses sustainable marketing st...
7,Forbes,"Marshall Shepherd, Senior Contributor, \n Mars...",Rowen Foundation Sees A Pathway To Sustainable...,Rowen Foundation is developing a research and ...,https://www.forbes.com/sites/marshallshepherd/...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T11:16:18Z,An artist rendition of the future Rowen commun...,8,The article is highly relevant as it discusses...
8,Forbes,"Namita Gupta-Hehl, Brand Contributor, \n Namit...",How Cloud ERP And AI Are Powering The Future O...,Cloud ERP and AI are uniquely positioned to he...,https://www.forbes.com/sites/sap/2025/04/28/ho...,https://imageio.forbes.com/specials-images/ima...,2025-04-28T13:27:29Z,Innovations in cloud ERP and AI are uniquely p...,9,The article focuses on how Cloud ERP and AI ca...

In [ ]:
# look at one row
next_df.iloc[0].rationale

'The article discusses innovative tech solutions aimed at well-being crises, which while valuable, do not directly address climate change or business solutions related to it. The focus on mental, physical, and financial well-being suggests an indirect relevance to climate change but lacks a direct connection to environmental innovation.'

In [ ]:
# look at an article title with small rating
print('title: ', next_df.sort_values(by='rating', ascending=True).iloc[0].title)
print('rating: ', next_df.sort_values(by='rating', ascending=True).iloc[0].rating)
print('rationale: ', next_df.sort_values(by='rating', ascending=True).iloc[0].rationale)

title:  This VC-backed network is on a mission to tackle the well-being crises with tech
rating:  4
rationale:  The article discusses innovative tech solutions aimed at well-being crises, which while valuable, do not directly address climate change or business solutions related to it. The focus on mental, physical, and financial well-being suggests an indirect relevance to climate change but lacks a direct connection to environmental innovation.

In [ ]:
# look at an article title with high rating
print('title: ', next_df.sort_values(by='rating', ascending=False).iloc[0].title)
print('rating: ', next_df.sort_values(by='rating', ascending=False).iloc[0].rating)
print('rationale: ', next_df.sort_values(by='rating', ascending=False).iloc[0].rationale)

title:  How Cloud ERP And AI Are Powering The Future Of Sustainability
rating:  9
rationale:  The article focuses on how Cloud ERP and AI can transform sustainability efforts for businesses, which directly relates to innovative business solutions combating climate change. It emphasizes practical applications and competitive advantages, highlighting a relevant and timely discussion in the context of sustainability.

In [ ]:
# sort dataframe by rating
next_df = next_df.sort_values(by='rating', ascending=False)

In [ ]:
# summarize whole articles
from newspaper import Config

summaries = []
for i in range(5):
  article_url = next_df.iloc[i]['url']
  text = Article(article_url)
  text.download()
  try:
    text.parse()
  except:
    user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
    config = Config()
    config.browser_user_agent = user_agent
    text = Article(article_url, config=config)
    text.download()
    text.parse()

  ai_input = text.text
  output_num_sents = 5
  base_messages = [
        {"role": "developer", "content": "You are a helpful AI assistant who will be asked to summarize articles."},
        {"role": "user", "content": f"Please summarize the following article using {output_num_sents} sentances:\n\n {ai_input}"}
    ]

  reply = client.chat.completions.create(
                messages=base_messages,
                temperature=1.0,
                top_p=1.0,
                max_tokens=1000,
                model=model_name
            )
  summaries.append({'article_idx':i, 'summary':reply.choices[0].message.content})

In [ ]:
summaries

[{'article_idx': 0,
  'summary': 'Innovations in cloud ERP and AI are essential for businesses aiming to transform sustainability challenges into competitive advantages. As climate change becomes a pressing concern, a significant number of executives are prioritizing sustainability, with 85% increasing their investments in this area. Technologies like SAP Green Ledger and SAP Green Token facilitate real-time tracking of carbon emissions and sustainable sourcing, enabling companies to enhance transparency and compliance while reducing their environmental impact. Furthermore, tools like Circelligence help organizations adopt circular economy principles, promoting efficient resource usage and waste reduction. Ultimately, leveraging these technologies allows companies not only to meet sustainability goals but also to thrive in an increasingly eco-conscious marketplace.'},
 {'article_idx': 1,
  'summary': 'The Rowen Foundation is developing a 2,000-acre living laboratory in Georgia aimed at fostering innovation, research, and community sustainability. The project has been designed with climate resilience and environmental stewardship integrated from the outset, utilizing advanced land-use strategies and infrastructure investments. Collaborating with notable institutions like the University of Georgia and Georgia Tech, Rowen plans to track and protect sensitive ecological areas while enhancing biodiversity. Its recent $32 million infrastructure investment emphasizes sustainable practices, reducing impervious surfaces and improving stormwater management. By establishing baseline environmental conditions, Rowen aims to inform best practices in climate resilience for future developers, positioning itself as a leader in sustainable community design amid increasing climate threats in the Southeast.'},
 {'article_idx': 2,
  'summary': 'At the recent Earth Day Women’s Summit in Dallas, Texas, a poll revealed that 100% of participants believe businesses are not doing enough to tackle the climate crisis, a sentiment echoed by a PwC 2024 study showing consumers’ readiness to pay more for sustainable products. The panel of business leaders discussed the importance of companies improving both internal operations and supply chain sustainability, as well as ensuring reliable power sources in the face of increasing climate-related disruptions. They highlighted key consumer concerns around packaging recyclability, credibility of certifications, and honest marketing communications, emphasizing that transparency is crucial for building trust. Additionally, the panel encouraged boards to maintain a long-term focus amidst various geopolitical and environmental challenges, stressing that sustainability should be integrated across all facets of business operations. Despite facing challenges, business leaders maintain that the pursuit of sustainability remains a critical imperative as environmental issues continue to escalate.'},
 {'article_idx': 3,
  'summary': "Andi Cross, founder of the impact consultancy WILDPALM, discusses the evolution of corporate leaders toward impact investing, emphasizing a shift from solely financial gains to prioritizing social and environmental outcomes. Impact investing balances profitability with purposeful initiatives, showcasing that capital can drive meaningful change, particularly in today's urgent economic climate. He highlights examples of impact-driven firms, such as New Ground Capital and Regeneration.VC, which focus on affordable housing and climate tech solutions, respectively. For startups seeking impact investors, integrating purpose from the outset, demonstrating market scalability, and effectively measuring impact are essential strategies. Ultimately, the future of business success lies in aligning long-term goals with resilience and sustainability, proving that profitability and positive impact can coexist."},
 {'article_idx': 4,
  'summary': "In today's business environment, sustainability has become essential rather than optional, with lean manufacturing emerging as a key strategy for reducing environmental impact. By focusing on eliminating waste, conserving resources, and streamlining operations, lean practices can significantly enhance both sustainability and commercial performance across an organization. Companies are encouraged to apply lean principles beyond production lines to include supply chains and logistics, which can further decrease scope 3 emissions. The transition to a circular economy, where products are designed for reuse and repair, complements lean thinking and presents opportunities for businesses to adopt greener practices without significant upfront costs through green financing. Furthermore, as consumer and regulatory demands for transparency grow, organizations must build sustainability into their culture and decision-making processes to meet expectations and drive long-term success."}]

Future work could include:
- adding more filtering capability
- making an interactive chatbot that you can ask questions to regarding the content of articles